apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gaia
spec:
  serviceName: "gaia"
  replicas: 3
  selector:
    matchLabels:
      app: gaia
  template:
    metadata:
      labels:
        app: gaia
    spec:
      containers:
      - name: gaia
        image: your-registry/gaia:v7.1.0
        ports:
        - containerPort: 26657
        - containerPort: 26660  # Add this line for Prometheus metrics port
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
        volumeMounts:
        - name: data
          mountPath: /root/.gaia
        - name: config
          mountPath: /root/.gaia/config
      volumes:
      - name: config
        configMap:
          name: gaia-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi