apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gaia-monitor
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: gaia
  endpoints:
  - port: metrics
    interval: 15s